ibw_job_index:
    path:     /
    defaults: { _controller: "IbwJobeetBundle:Job:index" }
    methods:  GET

ibw_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "IbwJobeetBundle:Job:show" }
    requirements:
        id:  \d+

ibw_job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "IbwJobeetBundle:Job:preview" }
    requirements:
        token:  \w+


ibw_job_new:
    path:     /new
    defaults: { _controller: "IbwJobeetBundle:Job:new" }
    methods:  [GET, POST]


ibw_job_create:
    pattern:  /create
    defaults: { _controller: "IbwJobeetBundle:Job:create" }
    requirements: { _method: post }


ibw_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "IbwJobeetBundle:Job:edit" }
    methods:  [GET, POST]

ibw_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "IbwJobeetBundle:Job:update" }
    requirements: { _method: post|put }


ibw_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "IbwJobeetBundle:Job:delete" }
    methods:  DELETE

ibw_job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "IbwJobeetBundle:Job:publish" }
    requirements: { _method: post }

ibw_job_extend:
    pattern:  /{token}/extend
    defaults: { _controller: "IbwJobeetBundle:Job:extend" }
    requirements: { _method: post }

